import React, { useEffect, useState } from "react";

import {NavLink , useNavigate} from 'react-router-dom'

import axios from 'axios'


const FooterCards =()=>{

    const nav = useNavigate()

    const showAll =()=>{
  
        nav('/showall')
    
      }

    const [car , setCar] = useState([])

  const fetchData = async()=>{
    const resultData = await axios.get(`${process.env.REACT_APP_PUBLIC_API_URL}/cars`)
  
    setCar(resultData.data)
    console.log(resultData.data)

  }
  
  useEffect (()=>{
    fetchData(); 
  },[])

    return(
        <>

        {/* CAR FLUID OUTER CONTAINER STARTS  */}
        
              <div className="container-fluid" style={{ backgroundColor: "rgba(129, 178, 154, 0.8)"}}>
        
                <div className="container"  style={{paddingBottom:'100px'}}>
                    
                    <div className="d-flex justify-content-between" style={{paddingTop:'80px'}}>
                          <h1 className="mx-4 fw-bold">Featured Cars</h1>
                          <button className="btn btn-lg btn-warning px-5 py-2 mx-4" onClick={()=>{showAll()}}>Show All</button>
                    </div>
        
                    {/*     CARDS SECTION STARTS */}
                    {/* ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ */}
        
                    <div className="container mt-5">
                        <div className="row">
        
                            {
                                car.slice(0,4).map((val , index , array)=>{
                                    return(
                                        <div className="col-md-3 my-3" key={index}>
                                <div className="card rounded-4">
                                    <div className="card-body">
                                        {/* img-fluid for image  */}
                                        <div>
                                             <span className="btn btn-warning px-3 py-0" style={{position:"absolute",right:'30px', top:'24px' }}>{val.cYear}</span>
                                             <img src={val.cImg} alt="" className="img-fluid rounded"/>
                                        </div>
                                        <h5 className="mt-4">{val.cName}</h5>
        
                                    <div><span>{val.cCurrency}</span>
                                         <span className="fw-bold fs-4">{val.cMoney}</span>
                                         <span>{val.cDay}</span>
                                    </div>
                                    
                                    {/* milage section // different object */}
                                    <div className="d-flex justify-content-around mt-3 p-2 rounded-4" style={{backgroundColor:"rgba(1,1,1,0.15)"}}>
                                        <div className="d-flex flex-column"><span><img src="/images/card-svg/mileage-icon.svg" alt="" height={"25px"}/></span>
                                        <span style={{fontSize:"15px", textAlign:"center"}}>{val.mileage}</span></div>
        
                                        <div className="d-flex flex-column text-center"><span><img src="/images/card-svg/transmission-icon.svg" alt="" height={"25px"}/></span> <span style={{fontSize:"15px", textAlign:"center"}}>{val.type}</span></div>
        
                                        <div className="d-flex flex-column"><span><img src="/images/card-svg/seats-icon.svg" alt="" height={"25px"}/></span>
                                        <span style={{fontSize:"15px", textAlign:"center"}}>{val.person}</span></div>
        
                                        <div className="d-flex flex-column"><span><img src="/images/card-svg/baggage-icon.svg" alt="" height={"25px"}/></span>
                                        <span style={{fontSize:"15px", textAlign:"center"}}>{val.bags}</span></div>
                                    </div>
        
                                        {/* just used navlink and redirected to `showall/cardetails/${val.cId}` page for details */}

                                        {/* Never use id associated with entity => USE ID INTEAD OF GENERATED BY API BY ITSELF */}

                                        {/* ${val.cId} */}
                                        {/* <div className="text-center mt-4"><NavLink to={`/showall/cardetails/${val.cId}`} className="btn btn-warning rounded-4">{val.cButton}</NavLink></div> */}

                                        {/* ${val.id} */}
                                        <div className="text-center mt-4"><button onClick={()=>{nav(`/cardetailed/${val.id}`)}} className="btn btn-info rounded-4">{val.cButton}</button></div>
                                    
        
                                    </div>
                                </div>
                            </div>
                                    ) //ending of return
                                })
                            }
        
                        </div>
                    </div>
        
                    {/* CAR CARD SECTION END */}
                    {/* $$$$$$$$$$$$$$$$$$$$$ */}
        
                </div>
              {/* SIMPLE CONTAINER END */}
        
              </div>
              {/* FLUID CONTAINER END */}
        
        </>
    )
}

export default FooterCards ;